### PR TITLE
Support for IPv6 Host

### PR DESCRIPTION
**Pull request by SaadHassan-dev**
- Added support for IPv6 host
- Version bumped to 2.2.0

### CODE REVIEW

**Review by UmanShahzad — COMMENTED** [review]
Note the model followed by https://github.com/ipinfo/go/pull/62/files is to allow the user a new function to make a v6 request separately as needed, instead of exclusively one or the other.

**Review by UmanShahzad — COMMENTED** [review]
- If we rapidly switch between v4/v6 calls this will keep on creating a new adapter. My thinking was you could just modify the host URL only within the existing adapter directly, if that's possible? Otherwise if that's not possible, and an adapter isn't e.g. caching network connections per adapter (e.g. in an internal connection pool), we could just instantiate 2 at the beginning for v4/v6 and use them accordingly. Or if adapters do cache network connections, then we could just do lazy initialization of the adapters and keep them both, worse case.
- We don't need a `_v6` call for every function, really just details_v6 because we want the requester v6 IP - you can already get v6 IP data for input v6 IPs via the other APIs without a v6.ipinfo.io host.

**Comment by SaadHassan-dev** [comment]
Previously, we used to set up connections with a fixed base URL that couldn't be modified afterward. Now, we are creating connections where the entire URL is specified at the time of the request. This gives us the flexibility to direct requests to either the 'v6' or 'v4' host as needed.

**Review by UmanShahzad — APPROVED** [review]
Powerful now! Exactly what we want

**Pull request merged**
